[profile.default]
solc-version = "0.8.18"
viaIR = true
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer-runs = 10_000_000
remappings = [
    '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts',
    '@solmate=lib/solmate/src/',
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
